cellsize: 0.1
numangles: 16
actions:
    - dx:  1.0
      dy:  0.0
      rv:  0.0
      dt:  0.1
    - dx:  1.0
      dy:  0.0
      rv:  4.0
      dt:  0.1
    - dx:  1.0
      dy:  0.0
      rv:  -4.0
      dt:  0.1
    - dx:  1.0
      dy:  0.0
      rv:  4.0
      dt:  0.1
    - dx:  1.0
      dy:  0.0
      rv: -4.0
      dt:  0.1