named_indices: { left_wam:      [11,12,13,14,15,16,17],
                 left_manip:    [18,19,20,21],
                 left_fingers:  [18,19,20],
                 right_wam:     [0,1,2,3,4,5,6],
                 right_manip:   [7,8,9,10],
                 right_fingers: [7,8,9] }

home:           { right_wam:      [ 3.68, -1.90,  0.00,  2.20,  0.00,  0.00,  0.00 ],
                  right_manip:    [ 0.00,  0.00,  0.00,  0.00 ],
                  left_wam:       [ 2.60, -1.90,  0.00,  2.20,  0.00,  0.00,  0.00 ],
                  left_manip:     [ 0.00,  0.00,  0.00,  0.00 ] }

relaxed_home:   { right_wam:      [ 5.65, -1.76, -0.26,  1.96, -1.15 , 0.87, -1.43 ],
                  right_manip:    [ 3.14,  3.14,  3.14,  0.00 ],
                  left_wam:       [ 0.64, -1.76,  0.26,  1.96,  1.16,  0.87,  1.43 ],
                  left_manip:     [ 3.14,  3.14,  3.14,  0.00 ] }

vertical:       { right_wam:      [ 3.14, -1.57,  0.00,  0.00,  0.00,  0.00,  0.00 ],
                  right_manip:    [ 0.00,  0.00,  0.00,  0.00 ],
                  left_wam:       [ 3.14, -1.57,  0.00,  0.00,  0.00,  0.00,  0.00 ],
                  left_manip:     [ 0.00,  0.00,  0.00,  0.00 ] }

relaxed:        { right_wam:      [ 5.73, -1.82, -0.35,  1.87, -4.06, -0.66,  0.98 ],
                  right_manip:    [ 2.40,  2.40,  2.40,  0.00 ],
                  left_wam:       [ 0.55, -1.82,  0.35,  1.87, -2.22, -0.66, -0.98 ],
                  left_manip:     [ 2.40,  2.40,  2.40,  0.00 ] }

carry_pose:     { right_wam:      [ 3.47, -1.56,  0.24,  2.86, -1.81, -1.38, -1.31 ],
                  right_manip:    [ 2.40,  2.40,  2.40,  0.00 ],
                  left_wam:       [ 2.81, -1.56, -0.24,  2.86, -4.47, -1.38,  1.31 ],
                  left_manip:     [ 2.40,  2.40,  2.40,  0.00 ] }

fingers_open:   { right_fingers:  [ 0.00,  0.00,  0.00 ],
                  left_fingers:   [ 0.00,  0.00,  0.00 ]}

fingers_closed: { right_fingers:  [ 2.40,  2.40,  2.40 ],
                  left_fingers:   [ 2.40,  2.40,  2.40 ] }

